CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun  --nnodes=1 --nproc_per_node=8 --master_addr localhost --master_port 7428 --node_rank 0 train.py \
    --model_name_or_path meta-llama/Llama-3.1-8B-Instruct \
    --dataset_name ../data/dpo/processed/train \
    --trust_remote_code \
    --max_length 8192 \
    --max_prompt_length 8000 \
    --output_dir ../save_model/llama \
    --save_steps 500 \
    --gradient_accumulation_steps 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --learning_rate 5e-7 \
    --logging_strategy steps \
    --logging_steps 50 \
    --logging_dir ../save_model/llama \
    --bf16 True \
    --num_train_epochs 1 \
    --report_to "tensorboard" \
    --save_only_model \
    --gradient_checkpointing \
    --deepspeed ../config/ds_config_zero3.json
